### ISSUE TITLE
Client setup error

### ISSUE THREAD

**Issue by wldtrky** [sjmh/pyqb#2]
root@local-0UN:~# python
Python 2.7.12 (default, Nov 20 2017, 18:23:56)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyqb
>>> qbc = pyqb.Client(username='shawn', password='test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() got an unexpected keyword argument 'username'
>>>

**Comment by sjmh** [comment]
@wldtrky Looks like I need to fix the documentation.

You don't pass the username during the creation of the Client.  You only pass it when doing an authenticate call.

```
import pyqb
qbc = pyqb.Client(database='mydb')
qbc.authenticate(username='shawn', password='test')
```

**Comment by eww125** [comment]
I also have an issue getting this to work. The first problem is the print statement looks like Python 2.7 without parentheses.

```
  File "/usr/local/lib/python3.6/dist-packages/pyqb/__init__.py", line 115
    print request
                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(request)?
```

The second issue I see is that the code seems ambiguous, do we uncomment the 'def' function and indent the second line? In other words, does

```
import pyqb
# def Client(username=None, password=None, url="http://www.quickbase.com", database=None):
qbc = pyqb.Client(username='myusername', password='mypassword')
```

become

```
import pyqb
def Client(username=None, password=None, url="http://www.quickbase.com", database=None):
    qbc = pyqb.Client(username='myusername', password='mypassword')
```


?
And if so, do we need to return qbc?
