### ISSUE TITLE
pip installs an older version

### ISSUE THREAD

**Issue by avinashjoshi** [sjmh/pyqb#9]
`pip install pyqb` installs an older version of this package. What's the best way to update PyPI with the current master - https://pypi.org/project/pyqb/?

**Comment by sjmh** [comment]
@avinashjoshi sorry about this - work has been a little crazy lately.  I'll try and get the latest master branch up into pypi by next week.

**Comment by avinashjoshi** [comment]
No worries, I was just wondering. For now, I just use `pip install git+https://github.com/sjmh/pyqb`

**Comment by grahamdavies** [comment]
I am also experiencing this issue. pip version does not support py3 - github version does.

**Comment by nickcatal** [comment]
@sjmh can you push the new version (which you just merged in) to pypi?

Thanks

**Comment by sjmh** [comment]
Will do - meant to do this earlier today but then got busy.

**Comment by sjmh** [comment]
apologies - have had to deal with the fires here in southern california lately. 0.2.3 is now up there
